on: push
jobs:
  first:
    runs-on: windows-latest
    steps:
      - run: node --version
      - run: npm --version
      - run: npm install electron@10.4.7 electron-builder
      - run: npx electron --version
      - run: npx electron-builder --version

      - name: Get version and name from package.json
        id: get_version_name
        run: |
          echo "::set-output name=version::$(node -p "require('./package.json').version")"
          echo "::set-output name=name::$(node -p "require('./package.json').name")"