on: push
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-12]

    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - run: npm install electron@10.4.7 electron-builder --save-dev

      - id: get_version_name
        run: echo "::set-output name=version::$(node -p "require('./package.json').version")"

      - uses: softprops/action-gh-release@v2.0.6
        # env:
        #   GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}      
        with:
          tag_name: v${{ steps.get_version_name.outputs.version }}
          name: ${{ steps.get_version_name.outputs.version }}
          draft: true
          prerelease: false
          token: ${{ secrets.GITHUB_TOKEN }}

      - run: npm run build
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}