on: push
jobs:
  first:
    runs-on: windows-latest
    steps:
      - run: node --version
      - run: npm --version
      - run: npm install electron electron-builder
      - run: electron --version
      - run: electon-builder --version